[package]
name = "majjit"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-to-tui = "7.0.0"
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
crossterm = "0.29.0"
indexmap = "2.10.0"
ratatui = "0.29.0"
regex = "1.11.1"
